version: "3.4"

services:
  namenode:
    image: hadoop-namenode:3.3.1
    container_name: namenode
    hostname: namenode
    ports:
      - "50070:50070"
      - "9000:9000"
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - /tmp/hadoop_tmp:/tmp
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_bridge

  datanode:
    image:  hadoop-datanode:3.3.1
    container_name: datanode
    hostname: datanode
    restart: always
    volumes:
      - datanode:/opt/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_bridge

volumes:
  namenode:
  datanode:

networks:
  hadoop_bridge:
