version: "3.4"

services:
  namenode:
    image: hadoop-namenode:3.3.1
    container_name: namenode
    hostname: namenode
    ports:
      - 50070:50070
      - 9000:9000
      - 8088:8088
      - 9866:9866
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - /tmp/hadoop_tmp:/tmp
    env_file:
      - ./hadoop.env
    links:
      - datanode

  datanode:
    image:  hadoop-datanode:3.3.1
    container_name: datanode
    hostname: datanode
    restart: always
    volumes:
      - datanode:/opt/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
volumes:
  namenode:
  datanode:
